"use client";

import React, { useState, useEffect } from "react";
import { db } from "@/lib/firebase";
import { 
  collection, 
  query, 
  where, 
  getDocs, 
  deleteDoc, 
  doc, 
  updateDoc,
  getDoc
} from "firebase/firestore";
import { useAuth } from "@/context/AuthContext";
import { AuthGuard } from "@/components/AuthGuard";

export default function CleanupPage() {
  const { user } = useAuth();
  const [status, setStatus] = useState<string>("Ready");
  const [results, setResults] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchSuspicious = async () => {
    if (!user) return;
    setLoading(true);
    setStatus("Fetching suspicious data...");
    
    try {
      const portfolioId = "default";
      const transCol = collection(db, "users", user.uid, "portfolios", portfolioId, "transactions");
      const assetsCol = collection(db, "users", user.uid, "portfolios", portfolioId, "assets");
      
      const tSnap = await getDocs(transCol);
      const aSnap = await getDocs(assetsCol);
      
      const suspiciousTransactions = tSnap.docs
        .map(d => ({ id: d.id, ...d.data() } as any))
        .sort((a, b) => (b.quantity || 0) - (a.quantity || 0))
        .slice(0, 50);
        
      const suspiciousAssets = aSnap.docs
        .map(d => ({ id: d.id, ...d.data() } as any))
        .sort((a, b) => (b.quantity || 0) - (a.quantity || 0))
        .slice(0, 50);
        
      setResults([{ transactions: suspiciousTransactions, assets: suspiciousAssets }]);
      setStatus(`Found ${tSnap.docs.length} transactions and ${aSnap.docs.length} assets.`);
    } catch (err: any) {
      console.error(err);
      setStatus(`Error: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const performCleanup = async () => {
    if (!user) return;
    setLoading(true);
    setStatus("Cleaning up isAutoGenerated transactions...");
    
    try {
      const portfolioId = "default";
      const transCol = collection(db, "users", user.uid, "portfolios", portfolioId, "transactions");
      const assetsCol = collection(db, "users", user.uid, "portfolios", portfolioId, "assets");
      
      const q = query(transCol, where("isAutoGenerated", "==", true));
      const snapshot = await getDocs(q);
      const docs = snapshot.docs;
      
      setStatus(`Found ${docs.length} auto-generated transactions. Deleting...`);
      
      const affectedAssetIds = new Set<string>();
      for (const d of docs) {
        const data = d.data();
        if (data.assetId) affectedAssetIds.add(data.assetId);
        await deleteDoc(d.ref);
      }
      
      setStatus(`Deleted ${docs.length} transactions. Recalculating ${affectedAssetIds.size} assets...`);
      // Re-run suspicious fetch to update list
      await fetchSuspicious();
      setStatus("Cleanup of isAutoGenerated complete.");
    } catch (err: any) {
      console.error(err);
      setStatus(`Error: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const deleteById = async (type: 'transaction' | 'asset', id: string) => {
    if (!user) return;
    try {
      const path = type === 'transaction' ? "transactions" : "assets";
      await deleteDoc(doc(db, "users", user.uid, "portfolios", "default", path, id));
      setStatus(`Deleted ${type} ${id}`);
      await fetchSuspicious();
    } catch (err: any) {
      setStatus(`Delete failed: ${err.message}`);
    }
  };

  const purgeAllTransactions = async () => {
    if (!user) return;
    setLoading(true);
    try {
      const transCol = collection(db, "users", user.uid, "portfolios", "default", "transactions");
      const snap = await getDocs(transCol);
      for (const d of snap.docs) {
        await deleteDoc(d.ref);
      }
      setStatus(`Purged all ${snap.docs.length} transactions.`);
      await fetchSuspicious();
    } catch (err: any) {
      setStatus(`Purge failed: ${err.message}`);
    } finally {
      setLoading(false);
    }
  }

  const resetAnalysisData = async () => {
    if (!user || !window.confirm("Delete all analysis metrics?")) return;
    setLoading(true);
    setStatus("Resetting analysis data...");
    try {
      const portfolioId = "default";
      const paths = ["growth", "summary", "behavior", "strategy"];
      for (const p of paths) {
        await deleteDoc(doc(db, "users", user.uid, "portfolios", portfolioId, "analysis", p));
      }
      setStatus("Analysis data reset successfully.");
      await fetchSuspicious();
    } catch (err: any) {
      setStatus(`Reset failed: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthGuard>
      <div className="p-10 max-w-6xl mx-auto space-y-6">
        <h1 className="text-2xl font-bold">NISA Data Investigation & Cleanup</h1>
        <div className="bg-slate-100 p-4 rounded-lg">
          <p className="font-mono text-sm">{status}</p>
        </div>
        <div className="flex gap-4">
          <button
            onClick={performCleanup}
            disabled={loading}
            className="bg-rose-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-rose-700 disabled:opacity-50"
          >
            Run Auto-Cleanup (isAutoGen)
          </button>
          <button
            onClick={fetchSuspicious}
            disabled={loading}
            className="bg-indigo-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-indigo-700 disabled:opacity-50"
          >
            Fetch Data
          </button>
          <button
            onClick={resetAnalysisData}
            disabled={loading}
            className="bg-amber-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-amber-700 disabled:opacity-50"
          >
            Reset Analysis Docs
          </button>
          <button
            onClick={purgeAllTransactions}
            disabled={loading}
            className="bg-black text-white px-6 py-3 rounded-lg font-bold hover:bg-slate-800 disabled:opacity-50"
          >
            PURGE ALL TRANSACTIONS
          </button>
        </div>

        {results.length > 0 && results[0].assets && (
          <div className="grid grid-cols-2 gap-8">
            <div>
              <h2 className="text-xl font-bold mb-4">Top Assets (Qty)</h2>
              <div className="space-y-2 max-h-[500px] overflow-y-auto">
                {results[0].assets.map((a: any) => (
                  <div key={a.id} className="p-2 border rounded text-xs flex justify-between items-center">
                    <span>{a.name} ({a.symbol}): {Number(a.quantity).toLocaleString()}</span>
                    <button onClick={() => deleteById('asset', a.id)} className="text-rose-600 font-bold ml-2 underline">DEL</button>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <h2 className="text-xl font-bold mb-4">Top Transactions (Qty)</h2>
              <div className="space-y-2 max-h-[500px] overflow-y-auto">
                {results[0].transactions.map((t: any) => (
                  <div key={t.id} className="p-2 border rounded text-xs flex justify-between items-center">
                    <span>{t.assetId || t.assetSymbol} - Qty: {Number(t.quantity).toLocaleString()} - {t.memo || 'No memo'} {t.isAutoGenerated ? '(AUTO)' : ''}</span>
                    <button onClick={() => deleteById('transaction', t.id)} className="text-rose-600 font-bold ml-2 underline">DEL</button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </AuthGuard>
  );
}
